### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by NebulaGitHub** [Zwork101/tf2-trade-bot#3]
Hi, is this where i report that i am having a problem? anyways thanks so much for making this and making it for free, i just need some help i keep getting a message that says [trading.data]: Unable to find file
I do have a file called trade.data and this is what i have inside:
  item market name, ref price, <type (sell/buy)>
the killer exclusive,2,sell
the killer exclusive,1.88,buy
i am probably doing something wrong but help would be appreciated 
Also i was getting a message early that my username or password or secrets where no valid, i put that information already, wondering if that has anything to do?
Also there are brackets on ref price and item market name, though it doesn't show so i took them off
Anyways thanks for your time!

**Comment by Zwork101** [comment]
First, make sure the file trade.data is inside the same folder as bot.py, second, take out, the item market name, ref price, <type (sell/buy)> at the top of the file, that was just a reference! Thanks for using tf2-trade-bot, this is very new, and I want to make sure everything is working just dandy!

**Comment by Zwork101** [comment]
And yes, this is where you make issues, and if you would like to make one in private, you can email me via my github profile

**Comment by Zwork101** [comment]
@NebulaGitHub In addition, it's caps sensitive, which might be somthing to change in the future, however, for now, use The Killer Exclusive, and not the killer exclusive, please tell if this works for you! Thanks!

**Comment by NebulaGitHub** [comment]
So i renamed file to trading.data and now its working.
Don't put any brackets when writing 
Ex. The Killer Exclusive,2,sell
Thanks for your help Zwork101!

**Comment by Zwork101** [comment]
Looks good! Make sure to report any issues right away <3
